version: "3.7"

services:
  jerni-mongodb:
    container_name: jerni-mongodb
    image: mongo:latest
    volumes:
      - "${MONGODB_DIR}:/var/lib/mongodb"
    env_file:
      - ".env"
    networks:
      - common
  jerni-redis:
    container_name: jerni-redis
    image: redis:latest
    networks:
      - common
  jerni-api:
    container_name: jerni-api
    image: jerni-api:latest
    ports:
      - "${PORT}:3000"
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
      - "MONGODB_URI=mongodb://jerni-mongodb:27017"
      - "MONGODB_DBNANME=jerni"
      - "REDIS_URI=redis://jerni-redis:6379"
    env_file:
      - ".env"
    networks:
      - common

networks:
  common:
