version: "3.7"

services:
  mongodb:
    container_name: tdb-mongodb
    image: mongo:latest
    volumes:
      - "${MONGODB_DIR}:/data/db"
    env_file:
      - ".env"
    networks:
      - common
  redis:
    container_name: tdb-redis
    image: redis:latest
    networks:
      - common
  tdb-server:
    container_name: tdb-server
    build: "."
    image: tdb-server:latest
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV="production"
      - MONGODB_URL="mongodb://tdb-mongodb:27017"
      - REDIS_URI="redis://tdb-redis:6379"
    env_file:
      - ".env"
    networks:
      - common

networks:
  common:
