version: '3'

services:
  tdb-server:
    container_name: tdb-server
    build: .
    image: tdb-server:latest
    ports:
      - '3000:3000'
    env_file: .env.production
    networks:
      - common
  mongodb:
    container_name: tdb-mongodb
    image: mongo:latest
    ports:
      - '3100:27017'
    volumes:
      - './.docker/mongodb:/data/db'
    networks:
      - common
  redis:
    container_name: tdb-redis
    image: redis:latest
    ports:
      - '3200:6379'
    volumes:
      - './.docker/redis:/data/redis'
    networks:
      - common

networks:
  common:
